# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161020_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ordre', 'verbose_name_plural': 'Orders'},
        ),
    ]
