# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161020_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ordre', 'verbose_name_plural': 'Orders'},
        ),
    ]
